### ISSUE TITLE
[deploys] Netlify build image needs an update

### ISSUE THREAD

**Issue by isms** [drivendataorg/nbautoexport#116]
Looks like an easy fix, but for now this is the message:

> Support for the Xenial build image ended on November 15, 2022. To enable builds for this site, select another build image. [Read the migration guide](https://answers.netlify.com/t/please-read-end-of-support-for-xenial-build-image-everything-you-need-to-know/68239).

**Comment by pjbull** [comment]
I "unlinked" the repository, and confirmed that publishing with the API from GitHub actions still works:

<img width="1239" alt="image" src="https://user-images.githubusercontent.com/1799186/223527500-6727ec41-5a87-482b-a838-e076276a13ef.png">
