### ISSUE TITLE
Write integration test that triggers post-save with Jupyter saving

### ISSUE THREAD

**Issue by ejm714** [drivendataorg/nbautoexport#5]
But how do we generate a save?

**Comment by mwouts** [comment]
Hi there. Did you try instantiating a contents manager? I think you could configure your own post save hook, and then call `cm.save`. I have many examples in which `cm.save` is called at https://github.com/mwouts/jupytext/blob/master/tests/test_contentsmanager.py .

**Comment by jayqi** [comment]
Thanks for your help @mwouts, that was exactly the tip we needed.
